### ISSUE TITLE
securityContext, shareProcessNamespace are lost on resource kind deployments

### ISSUE THREAD

**Issue by hightoxicity** [stakater/Konfigurator#36]
Hi,

I think there is an issue on deployment update, since if you had set securityContext or shareNamespace, all of this are lost when konfigurator updates resources to inject mount points...

Thx.

**Comment by hightoxicity** [comment]
The test is passing maybe the bug come from the kube dependencies...

**Comment by rasheedamir** [comment]
Not reproducible; plz re-open if this issue still exists
